### ISSUE TITLE
At startup screen - make party, quit, select "save first" - it doesn't quit

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#148]
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here.

**Comment by NQNStudios** [comment]
@CelticMinstrel this bug happens because the logic of this statement (and its repetitions elsewhere) is inverted:
https://github.com/calref/cboe/blob/0a3aa97b59627a05144f9d2b58ea21df003ae42b/src/game/boe.main.cpp#L612

It's not quitting, and it's not saving, either. We just need to delete the `!`, because i think this statement was meant to short-circuit the quitting if they cancel the file browser dialog.

In PR #381 the problematic statement is de-duplicated so it will be best to fix this after #381 is merged.

Incidentally I debugged this one using the replay system, which I've made a separate repo for storing a replay test suite in: https://github.com/NQNStudios/cboe-replay-testing

**Comment by NQNStudios** [comment]
Actually, removing the `!` doesn't fully make this case flow completely correctly. After saving, now it still warns the player "If you quit now, your game will be lost" and that's wrong.

**Comment by CelticMinstrel** [comment]
> After saving, now it still warns the player "If you quit now, your game will be lost" and that's wrong.

This should happen when the mode is anything other than town, outdoors, or startup. It certainly shouldn't ever happen after actually _asking_ to save.
