### ISSUE TITLE
Cannot exceed 8x8 for outdoor areas

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#161]
If I try to make an outdoors bigger than 8x8 or so (can't remember the number) it tells me I can't have more than 100 outdoor sections.
Then, changing the number will not help. It keeps giving the error until I cancel out.

---
This is an item logged from the To-Do and was originally reported by ADoS. If you are familiar with or can recreate this bug, please provide details here

**Comment by CelticMinstrel** [comment]
Looks like this bug is moot, because I've removed the limitation on total number of outdoor sectors. In fact, I've even removed the limitation on width and height of the outdoors, so I guess the dialog should be updated to reflect this (it still claims there's a limit).

In any event, this issue no longer is one.
