### ISSUE TITLE
New underground scenario: outdoor town entrance is wrong terrain

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#339]
![imagen](https://user-images.githubusercontent.com/2584745/216483735-ea0329b5-890f-4303-9ddc-bc468b8d416b.png)

![imagen](https://user-images.githubusercontent.com/2584745/216484247-41b0dd9d-d2e6-4e30-b4e6-024a9b4d332f.png)

**Comment by NQNStudios** [comment]
The default outdoor section of a new scenario in the editor looks like this. When you leave town, you can't get back in because it's a blocked terrain type, not a town entrance.

I think it goes wrong here: https://github.com/calref/cboe/blob/master/src/scenedit/scen.core.cpp#L3082

**Comment by NQNStudios** [comment]
Here are the terrains. Fire pit must be 232. 
![imagen](https://user-images.githubusercontent.com/2584745/216485336-8d825d79-de6a-426e-a043-02515252cecf.png)

There are 4 underground settlement terrains in the row below, but I don't know which one was the intended default.

**Comment by CelticMinstrel** [comment]
That would be because I added a bunch of extra terrains (to fill the empty spaces left by making roads and special spots be "fields" instead) and shifted the cave terrains up. I believe the intended terrain is the first cave town terrain, one down and to the left of the fire pit. You can probably verify this by opening the legacy base (under rsrc/legacy) and checking what terrain 232 is, though it wouldn't be the end of the world if we got it wrong.

That said, while we can certainly do a quick fix for this now, I think the correct fix in the long term is to use a different "base" scenario for an underground scenario. Then there would be no need to mod the terrain to make it be underground.

**Comment by NQNStudios** [comment]
> That said, while we can certainly do a quick fix for this now, I think the correct fix in the long term is to use a different "base" scenario for an underground scenario. Then there would be no need to mod the terrain to make it be underground.

Right. Linking to issue #249
