### ISSUE TITLE
VoDT first room - a Monster Saw You! followed by a crash

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#407]
I can load a party, enter VoDT, take a few steps around the first room, and get a buffer message "Monster saw you!"

If I keep taking steps around the room I get a crash with this error: "Attempt to access a player that doesn't exist." (The party has 6 members.)

Where the heck did these bugs come from?

First found these on Windows.

**Comment by NQNStudios** [comment]
Here's something wild. I ran `git bisect` to figure out which commit introduced the problem, and it was:

fc12092a1b1b2779141c917e2974bed0252ea5cf

"replace rand() and srand(). fix #390"

**Comment by CelticMinstrel** [comment]
I assume this is ported VoDT, not legacy VoDT, right? (You'd know if you were using the legacy one, because you would've had to specifically take steps to do so on purpose.)

This sounds similar to the old "uninitialized monster record is wrongly taken as valid" bug, but I'm not sure how that would be caused by the random number generator…

**Comment by CelticMinstrel** [comment]
I can't reproduce it on the Mac, but what I'd recommend doing is to set a breakpoint on the specific add_string_to_buf() call and step through from there to see what's happening.
