### ISSUE TITLE
Record and replay the remaining actions

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#409]
Known actions/systems that aren't supported yet in the replay system:
- [x] Look/search
- [x] buying items
- [x] selling items
- [x] start conversation with NPC
- [x] Ask NPC through preset buttons
- [x] Ask NPC through dynamic (word) buttons
- [x] Rest
- [x] Cast spells
- [x] Debug actions
- [x] z key to show inventory
- [x] type ? for contextual help (some cases are already handled by show_dialog_action)
- [x] use space
- [x] quests
- [x] special items
- [x] interrupt
- [x] rest of the PC pane
- [x] more ? buttons in different modes?
- [x] tab in dialogs with multiple text fields
- [x] changing a text field's selection with the mouse
- [x] delete key in text fields
- [x] shift+movement key selection in text fields
- [x] show item info
- [x] scroll up/down in item list

There will be more that I haven't thought of yet.

**Comment by NQNStudios** [comment]
- [ ] canceling a save dialog

**Comment by CelticMinstrel** [comment]
I was making a great big list of everything, but I was composing it on GitHub and lost it when the browser suddenly decided to switch pages.

I'll give a general overview and a few examples of what's missing though:

* Menu actions. Pretty much all the menu actions are missing. There are a few vital actions squirrelled away in the menus.
* Debug actions. It's debatable whether these are needed, but they exist. Press Shift+D and / for a nearly-complete list (it's missing Shift+I).
* Some keyboard-only actions, like Z, B, Shift+L, Shift+/
* Jobs and Special Items (in the inventory pane) - there exists no scenario that uses jobs, so that one might be a little tough to test
* Nearly all the PC pane actions are missing – almost everything in that panel is clickable
* Help buttons - pretty much every area has a little help button
* Use Space - closing a door, for example

I'm not sure why you listed picking up items as unsupported – it works right now.

**Comment by NQNStudios** [comment]
I forgot getting items uses a dialog, which made it trivial to record and replay so I already did it.

**Comment by CelticMinstrel** [comment]
Aside from talking and shopping, I think the main ones you still haven't covered in #412 are things in the party and inventory panels.

* Switch PCs
* PC info
* Check PC HP
* Check PC SP
* Item info
* Special Items (with use and info buttons)
* Quests (I think these just have an info button, but I'm not sure)
* Does give item work now in #412? I saw you handled text input but not sure if that covers give.

And probably a few toolbar buttons:

* Cast spell – or is that handled in #412?
* Use space (eg closing a door or shoving a crate without moving)
* Rest (outdoors)
* Save/load buttons (outdoors) – though to be honest I'd sorta like to replace these with something else. It's kinda silly that you have buttons for load/save outdoors but nowhere else. But I guess there just aren't enough actions that you can do outdoors…

**Comment by NQNStudios** [comment]
give item is handled.

I implemented field recording key events specially, because in every other control, key events get turned into click events which all get recorded in the same way, which is actually nice.

**Comment by CelticMinstrel** [comment]
Oh, that reminds me that I think you haven't covered any actions that are accessible only via the keyboard:

* The easter egg keys (though we could skip those, they don't really matter)
* The debug actions
* Bash door (B)
* Pick lock (Shift+L)
* Repeat spell (Shift+P and Shift+M)

I think that's all of them, but I'm not sure.

**Comment by CelticMinstrel** [comment]
> * more ? buttons in different modes?

Don't forget the one that's invisible for some reason when shopping. (Maybe you already got it, not sure.)

The only other thing that I can think of that you're missing from the list is viewing special items (with an info and possibly use button) and viewing quests (which I think have an info button as well).

I'll see if I can find anything else missing once the latest PR is merged.

**Comment by NQNStudios** [comment]
Closing as complete!

**Comment by CelticMinstrel** [comment]
Okay, so I'm just going to try doing _everything I can think of_ and see if anything slipped through, and note anything I notice here. We can open new issues if it uncovers something real.

1. In the about dialog, operating the scrollbar adds both `<scrollbar_setPosition>` and `<control_click>` to the replay. Is this correct?
2. This isn't related to the replay stuff, I assume, but asking Terrance about "bugs" yields a blank response.
3. What is `<arrow_button_click>`?
4. Closing the automap didn't get recorded. Not sure if this matters.
5. Selecting a monster from the monster menu didn't get recorded. This is just info so maybe it doesn't matter.
6. The "Wait" button in combat didn't get recorded.
7. The "Act" button in combat didn't get recorded. (I think the keyboard shortcut is `x`.)
8. I assume you skipped the &*() easter egg on purpose, since it does absolutely nothing useful.
9. Pressing Shift+Q blanked out the map until the next update (not related to replay stuff, I assume).

And just for good measure, here's the actual replay:

[test-replay.xml.gz](https://github.com/user-attachments/files/16882119/test-replay.xml.gz)

**Comment by NQNStudios** [comment]
1. I don't know, seems harmless?
2. Seems unrelated.
3. Some of the buttons in the PC status screen etc. play an animation when clicked using a function called `arrow_button_click()`. I don't know why the function is named that. This replay action is purely cosmetic--it replays the animation. All buttons which call this function also record their actual events as the first thing after the `arrow_button_click` element.
4. Seems important!
5. This is important if it opens a dialog. Because if it does, then the log will record events which require that dialog to be open. So on replay, it might crash because those events are invalid.
6. Important
7. Important
8. Yes
9. Sounds unrelated

**Comment by CelticMinstrel** [comment]
> 1. I don't know, seems harmless?

It's harmless in the about dialog case, as nothing _within_ the scroll panel can be interacted with. I'm not sure if it would become a problem if you decided to extend the replay system to the scenario editor… but that's not really something to worry about _now_.
