### ISSUE TITLE
no visual boom for fireball

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#459]
The boom animation was skipped--damage values didn't show, booms didn't show. Enemies just disappeared, leaving scorch mark and bloodstains.

**Comment by NQNStudios** [comment]
Flame gets a (fast) visual boom. Fireball really gets none

**Comment by NQNStudios** [comment]
This actually seems to happen with sound On, as well.

**Comment by NQNStudios** [comment]
There's a function fireball_space() which never gets called and can be deleted without breaking the compilation.

**Comment by CelticMinstrel** [comment]
Hmm…

We should start by evaluating whether each of those settings are still worth having.

* No special effects: Not sure
* Turn off terrain animation: Not sure
* Turn off frills: Not sure
* No sounds: Definitely worth keeping
* Show room descriptions repeatedly: Seems reasonable to keep, not sure if it actually works tho
* Never show instant help: Definitely worth keeping
* Reset instant help: Why is this an LED instead of a tinybutton? But certainly worth keeping
* Make game easier: No contest, keep it
* Fewer wandering monsters: Not sure
* No splash screen: Definitely worth keeping

In short, it may well be the case that it's easier and better to just _drop_ those three settings. I'm not sure however – though they're intended as performance settings, I could maybe imagine someone intensely disliking the animated terrain and wanting to turn it off.  But for the other two I find it hard to imagine someone would want to turn them off, and I sincerely doubt anyone has an old enough computer that they'd cause performance issues.

> Since we need to paginate the settings dialog anyway

I'm not taking this as a given. I still don't think we need to forcibly ensure that all dialogs are less tall than the main window. Maaaybe it would be fine to do that in the main game only, but certainly not in the scenario editor.

> would you mind if I change it so there are always 9 explosions, or at least a guaranteed explosion on the center square?

Don't change to always 9 explosions. I could accept a guaranteed explosion on the centre space though. If I recall correctly, doesn't it usually place ashes on the centre space? And that means there's still an explosion if you miss, which heads off someone thinking it didn't work.

> Without graphics frills you also don't see how much damage was done in the terrain window.

And this leads into the other thing, which is that if we _do_ want to keep those settings we'd need to make sure that enabling them doesn't have stupid side-effects like that. So, keeping them isn't necessarily less work than deleting them.

**Comment by NQNStudios** [comment]
I'd gladly cut those 3 settings and turn the "reset instant help" thing into a button.

**Comment by NQNStudios** [comment]
> I could accept a guaranteed explosion on the centre space though. If I recall correctly, doesn't it usually place ashes on the centre space? And that means there's still an explosion if you miss, which heads off someone thinking it didn't work.

Yes, there's always ash at the center. So we need an explosion animation to go off there or it looks like a bug.
