### ISSUE TITLE
Intro/"Welcome to Blades of Exile" dialog has broken formatting

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#465]
<img width="707" alt="Screenshot 2024-11-07 at 12 40 10 PM" src="https://github.com/user-attachments/assets/ecd41ae5-ff6f-4be3-a738-87ccb5e85528">

**Comment by NQNStudios** [comment]
I thought that setting a frameStyle on each of the text widgets would shed some light on why the relative layouts are so busted. It definitely revealed that things are FUBAR, but I still can't see how the frames relate to the relative positioning -- it seems like the relative positioning is wrong and inconsistent even according to the frames.

<img width="701" alt="WithOutlinesScreenshot" src="https://github.com/user-attachments/assets/6518f9bd-df9c-49c5-bf43-dc9e20f96f80">

**Comment by NQNStudios** [comment]
It's looking like I broke this when I optimized line breaking 😅

**Comment by CelticMinstrel** [comment]
I think what's happening here is that there is a mismatch between the code that calculates how much space is needed and the code that actually renders the text.

So that means that the height allotted by the calculation is overflowed when actually rendering, and as a result, the text overflows its bounds when rendering.

Since each text block is positioned relative to the previous one, we would need to fix the calculation.

**Comment by NQNStudios** [comment]
That’s the track i’m on.
