### ISSUE TITLE
macOS builds of Blades and ScenEd hang, CharEd doesn't

### ISSUE THREAD

**Issue by wrldwzrd89** [calref/cboe#51]
I compiled the code from source as of commit 20ff735. It compiles A-OK, but the main game and scenario editor both hang immediately when I try to run. I'm using macOS Sierra 10.12.3, with Xcode 8.2.1 providing the compilers, and Boost 1.63.0 / SFML 2.4.1 / ICU 58.2 versions of direct and indirect dependent libraries. The way it hangs is rather interesting: the app opens, it tries to switch to full-screen mode, and gets hung up at this point, never successfully switching over. The application is listed as Not Responding, also. The only way out is to kill it.

**Comment by CelticMinstrel** [comment]
The one thing I can think of that the scenario editor and game startup procedures share which the chared does not is threading. The game and scenario editor split off a thread to keep the program more responsive (at least enough to avoid spinning beachballs) during startup (mainly the splash screen, but also some loading of resources). The character editor does not do this, performing all the startup work in the same thread.

I'll add that Blades of Exile does not use full-screen mode at all. Its "full screen" mode is really just a window without a titlebar, sized to fill the screen. If I recall correctly, this was so that a) additional monitors behave instead of becoming useless and b) the menubar doesn't go away. It's been awhile though, so I might be misremembering.

**Comment by wrldwzrd89** [comment]
I double-clicked the com.spidweb.bladesofexile.plist file to open it with Xcode, added a new row "DisplayMode", type Number, value 5. Tried launching the build. No difference, sadly.

**Comment by CelticMinstrel** [comment]
By "no difference" do you mean it still attempts to create a screen-sized window? I seem to recall there was some caching mechanism in newer MacOS which means simply editing a plist file isn't sufficient to make the changes stick.

That said, if it _is_ a threading issue, it's not likely that the size of the window would matter. Maybe you could try building and running it with the threads sanitizer, if your XCode supports it? Mine is too old, or I'd do it myself.

**Comment by wrldwzrd89** [comment]
No, it doesn't manage to display the window. The menu bar disappears and the game's busy cursor spins during this time. I am able to Command-Tab to other applications while this is happening and use them normally. A Force Quit is the only way to kill the hung program.

**Comment by CelticMinstrel** [comment]
I think the menubar doesn't disappear when it's launching into windowed mode, but I can't remember...

I've been getting occasional crashes on startup, so maybe the cause of those is the same. I guess I'll try poring over the code to see if I can locate any problematic points. I suppose it might be useful to have a stack trace of where it's hanging for you, too.

**Comment by wrldwzrd89** [comment]
I'd produce one, but I'm not entirely sure how, if I'm building with SCons rather than Xcode.

**Comment by CelticMinstrel** [comment]
If you get a crash report dialog, that generally contains a stack trace, though it does need to be a debug build to really be useful... scons may not be doing a debug build. It does take things such as CXXFLAGS and LDFLAGS from the environment, I believe, so you could probably force a debug build that way (I don't remember what the clang flags would be for that).

**Comment by wrldwzrd89** [comment]
Unfortunately, the app never does crash. It just gets stuck and doesn't respond. I tried launching the app from the Terminal, as well as looking at Console, but in both cases no log messages were produced. Looks like I need to figure out how to make a debug build and generate a stack trace, which would help immensely in getting to the bottom of this.

**Comment by wrldwzrd89** [comment]
Hooray, I got a stack trace! After faffing around with environment variables and lldb for a bit, anyway.
[cboe_stack_trace_issue51.txt](https://github.com/calref/cboe/files/768350/cboe_stack_trace_issue51.txt)

**Comment by CelticMinstrel** [comment]
Hmm. Looks like a threading deadlock between the `draw_logo()` and `init_startup()` functions. Not entirely sure how to fix it yet, but I guess this is a start...

**Comment by CelticMinstrel** [comment]
For the record, thread 1 in the stack trace is stuck in the middle of rendering, while thread 2 is stuck in the middle of creating a texture into which to load an image. (So, both threads are using OpenGL.) I have no idea why that would be a deadlock though.

Since it does appear to be a threading issue, you should be able to get it to work by commenting out the lines that split off and join the thread, though obviously that's not a long-term solution. There doesn't seem to be any problems on my Mac when I do that, but I'm not sure about Windows; I'll have to test later.

The relevant lines are boe.main.cpp:177,184,188 and scen.main.cpp:126,151,153.

**Comment by wrldwzrd89** [comment]
Oh, I should mention that the most recent release on @CelticMinstrel's site doesn't hang in this way. So I believe this is fixed.
