### ISSUE TITLE
Can enter docks before getting supplies

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#75]
Town 0: Message telling player they “can’t enter” docks until they have supplies does not actually block them.

---

This is an item logged from the To-Do and was originally reported by BainIhrno. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
This might be promoted to a general game issue, but for now, I've labelled it as a scenario issue since that's how it was reported.

**Comment by x-qq** [comment]
This also happens in VoDT at the southern gates of starting town (Fort Talrus). The special on the gates is supposed to block movement but does not do so because its flag spec.ex1a is 0 when it should be not 0 to actually block movement.

I have tried loading this scenario from the original .exs file from the legacy dir and the same thing happened there.

So I suspect the problem is in the code that loads the legacy scenario format.

**Comment by CelticMinstrel** [comment]
Which means it'll need to be fixed both in the importer and in the main scenarios...

**Comment by CelticMinstrel** [comment]
Noting here so that I don't forget: the legacy importer for special node types 4, 11, 26 should not be identical. The code there is correct for 4, but 11 should set ex1a to 1 (ex2a doesn't matter), and I'm not quite sure on 26 but I suspect the same.

**Comment by CelticMinstrel** [comment]
Commit a495e778e705c8f268d509cf65af9d2d36c6c55c fixes the import bug, however we will also need to propagate the fix to the four prefab scenarios.

**Comment by CelticMinstrel** [comment]
I've propagated the fix to the scenarios in fd139c59de04101ed5760ced44563c9340f3648f and fixed Wandering Will Fight (by inspection) in 488e5a25706e781c30de56da3445cb7832a1cacd.
